// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpb4jcSq0NrxdOU5PrbYT0CdEqIY1NHZw',
    appId: '1:88193541674:web:ebe673b27a0889f7bc4553',
    messagingSenderId: '88193541674',
    projectId: 'unitrip-7dee5',
    authDomain: 'unitrip-7dee5.firebaseapp.com',
    storageBucket: 'unitrip-7dee5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUvUq7FePkIzk1-K2idEpg3YrW6LuM9o',
    appId: '1:88193541674:android:c9dd1bf8210fa9ecbc4553',
    messagingSenderId: '88193541674',
    projectId: 'unitrip-7dee5',
    storageBucket: 'unitrip-7dee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUy6vYKPjsDgqTPm_EaDdzfmVA97VZKuk',
    appId: '1:88193541674:ios:d64705736f3ffe54bc4553',
    messagingSenderId: '88193541674',
    projectId: 'unitrip-7dee5',
    storageBucket: 'unitrip-7dee5.firebasestorage.app',
    iosBundleId: 'com.example.viagensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUy6vYKPjsDgqTPm_EaDdzfmVA97VZKuk',
    appId: '1:88193541674:ios:d64705736f3ffe54bc4553',
    messagingSenderId: '88193541674',
    projectId: 'unitrip-7dee5',
    storageBucket: 'unitrip-7dee5.firebasestorage.app',
    iosBundleId: 'com.example.viagensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpb4jcSq0NrxdOU5PrbYT0CdEqIY1NHZw',
    appId: '1:88193541674:web:7c6e826db26143cabc4553',
    messagingSenderId: '88193541674',
    projectId: 'unitrip-7dee5',
    authDomain: 'unitrip-7dee5.firebaseapp.com',
    storageBucket: 'unitrip-7dee5.firebasestorage.app',
  );

}